listen_address = "0.0.0.0:9001"
num_web_server_threads = 1
num_relay_threads = 1
max_actor_cache_size = 10000
protocol = "https"

instance = "smartlike.example.com"
name = "smartlike"
summary = "smartlike"

# Fediverse RSA keys
public_key = ""
private_key = ""

network_address = "https://smartlike.org/network"
smartlike_account = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
smartlike_key = "xxxx xxxxxxx xxxx xxxxxx xxxxx xxxxxx xxxxx xxxxxxx xxxxx xxxx xxxxx xxxx"

